# Generated by Django 5.1.3 on 2024-12-03 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='academic_degree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Ученая степень',
                'verbose_name_plural': 'Ученые степени',
            },
        ),
        migrations.CreateModel(
            name='code_programm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Код учебной программы',
                'verbose_name_plural': 'Коды учебных программ',
            },
        ),
        migrations.CreateModel(
            name='event_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Тип мероприятия')),
            ],
            options={
                'verbose_name': 'Тип мероприятия',
                'verbose_name_plural': 'Типы мероприятий',
            },
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='result_file',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Результат выполнения задания',
                'verbose_name_plural': 'Результаты выполнения заданий',
            },
        ),
        migrations.CreateModel(
            name='status_check',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус выполнения задания',
                'verbose_name_plural': 'Статусы выполнения заданий',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SURNAME', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('NAME', models.CharField(max_length=20, verbose_name='Имя')),
                ('PATRONYMIC', models.CharField(max_length=20, verbose_name='Отчество')),
                ('DATE_OF_BIRTH', models.DateField(verbose_name='Дата рождения')),
                ('email', models.CharField(max_length=24, verbose_name='Email')),
                ('PHONE_NUMBER', models.CharField(max_length=20, verbose_name='Телефон')),
                ('SEX', models.CharField(choices=[('man', 'мужчина'), ('woman', 'женщина')], max_length=10, verbose_name='Пол')),
                ('ADDRESS', models.CharField(max_length=256, verbose_name='Адрес')),
                ('DATE_START_STUDY', models.DateField(verbose_name='Дата начала обучения')),
            ],
            options={
                'verbose_name': 'Студенты',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='subject_classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид учебной дисциплины',
                'verbose_name_plural': 'Виды учебных дисциплин',
            },
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
                ('DEADLINE', models.DateField(verbose_name='Срок сдачи')),
                ('NOTE', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Задания',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='task_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид задания',
                'verbose_name_plural': 'Виды заданий',
            },
        ),
        migrations.CreateModel(
            name='education_programm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
                ('CODE', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.code_programm', verbose_name='Код учебной программы')),
                ('SUBJECTS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.subject', verbose_name='Предметы')),
            ],
            options={
                'verbose_name': 'Учебная программа',
                'verbose_name_plural': 'Учебная программа',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='TASKS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.task', verbose_name='Задания'),
        ),
        migrations.CreateModel(
            name='assessment_sheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('COMMENT', models.CharField(max_length=256, verbose_name='Комментарий')),
                ('EDUCATION_PROGRAMM', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.education_programm', verbose_name='Код учебной программы')),
                ('RESULT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.result_file', verbose_name='Результат')),
                ('STATUS_CHECK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.status_check', verbose_name='Статус выполнения задания')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.student', verbose_name='Студент')),
                ('SUBJECT', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.subject', verbose_name='Предмет')),
                ('TASK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Ведомость оценок',
                'verbose_name_plural': 'Ведомость оценок',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='TYPE_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.task_type', verbose_name='Тип работы'),
        ),
        migrations.AddField(
            model_name='subject',
            name='CLASSIFICATION',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.task_type', verbose_name='Тип дисциплины'),
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SURNAME', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('NAME', models.CharField(max_length=20, verbose_name='Имя')),
                ('PATRONYMIC', models.CharField(max_length=20, verbose_name='Отчество')),
                ('DATE_OF_BIRTH', models.DateField()),
                ('email', models.CharField(max_length=24, verbose_name='Email')),
                ('PHONE_NUMBER', models.CharField(max_length=20, verbose_name='Телефон')),
                ('ACADEMIC_DEGREE_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.academic_degree', verbose_name='Ученая степень')),
                ('POSITION', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.position', verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NOTE', models.CharField(max_length=256, verbose_name='Описание')),
                ('DATE_EVENT', models.DateField(verbose_name='Дата мероприятия')),
                ('TYPE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.event_type', verbose_name='Тип события')),
                ('VISITERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.student', verbose_name='Участники')),
                ('TEACHER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
