# Generated by Django 5.1.3 on 2024-12-03 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_education_programm_subjects_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterField(
            model_name='assessment_sheet',
            name='COMMENT',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='assessment_sheet',
            name='RESULT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.result_file', verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='CLASSIFICATION',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.subject_classification', verbose_name='Тип дисциплины'),
        ),
    ]
